# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='email',
            field=models.CharField(default='anonymous@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
    ]
