# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170416_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='email',
            field=models.EmailField(default='anonymous@example.com', max_length=200, unique=True),
        ),
    ]
