# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
