# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170417_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
