# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_delete_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
