# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_emails', '0002_auto_20161018_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberemail',
            name='subscription_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date subscribed'),
        ),
    ]
