# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('get_emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberemail',
            name='subscribed',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriberemail',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='subscriberemail',
            name='site_code',
            field=models.CharField(choices=[('gr', 'groja.com'), ('sm', 'seeourminds.com'), ('tw', 'tomwhartung.com'), ('th', 'tomhartung.com'), ('xx', 'site_unknown')], default='xx', max_length=2),
        ),
        migrations.AlterField(
            model_name='subscriberemail',
            name='subscription_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 18, 21, 41, 50, 316838, tzinfo=utc), verbose_name='date subscribed'),
        ),
    ]
